export const USERS = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@gmail.com",
    ratings: 4.5,
    password: "123456",
    reviews: [
      {
        id: 1,
        user: "tohn.doe@gmail.com",
        product_id: 1,
        rating: 4.5,
        comment: "This is a great shoe!",
      },
      {
        id: 2,
        user: "wohn.doe@gmail.com",
        product_id: 2,
        rating: 4.5,
        comment: "This is a great shoe!",
      },
    ],
  },
  {
    id: 2,
    name: "Tohn Doe",
    email: "tohn.doe@gmail.com",
    ratings: 4.2,
    password: "123456",
  },
  {
    id: 3,
    name: "Wohn Doe",
    email: "wohn.doe@gmail.com",
    ratings: 4.8,
    password: "123456",
  },
];

export const PRODUCTS = [
  {
    id: 1,
    shoe_name: "Air Jordan 1 Mid",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 120,
    condition: "New",
    isNewRelease: true,
    brand: "Air Jordan",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 2,
    shoe_name: "Nike Air Force 1 Low",
    seller: "john.doe@gmail.com",
    size: "9",
    price: 100,
    condition: "Used",
    brand: "Nike",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 3,
    shoe_name: "Adidas Yeezy Boost 350 V2",
    seller: "john.doe@gmail.com",
    size: "11",
    price: 250,
    condition: "New",
    brand: "Adidas",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 4,
    shoe_name: "Nike Dunk Low",
    seller: "john.doe@gmail.com",
    size: "8.5",
    price: 150,
    condition: "New",
    brand: "Nike",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 5,
    shoe_name: "New Balance 550",
    seller: "john.doe@gmail.com",
    size: "10",
    price: 100,
    condition: "Used",
    brand: "New Balance",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 6,
    shoe_name: "Vans Old Skool",
    seller: "john.doe@gmail.com",
    size: "7.5",
    price: 50,
    condition: "New",
    brand: "Vans",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 7,
    shoe_name: "Converse Chuck Taylor All Star",
    seller: "john.doe@gmail.com",
    size: "9.5",
    price: 60,
    condition: "Used",
    brand: "Converse",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 8,
    shoe_name: "Puma Suede Classic",
    seller: "john.doe@gmail.com",
    size: "8",
    price: 70,
    condition: "New",
    brand: "Puma",
    color: "Black",
    isNewRelease: true,

    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 9,
    shoe_name: "ASICS Gel-Lyte III",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 110,
    condition: "Used",
    brand: "ASICS",
    color: "White",
    isNewRelease: true,
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 10,
    shoe_name: "Saucony Shadow 6000",
    seller: "john.doe@gmail.com",
    size: "9",
    price: 120,
    condition: "New",
    brand: "Saucony",
    color: "Black",
    isNewRelease: true,

    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 11,
    shoe_name: "New Balance 990v5",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 150,
    condition: "Used",
    brand: "New Balance",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 12,
    shoe_name: "Air Jordan 1 High",
    seller: "john.doe@gmail.com",
    size: "10",
    price: 170,
    condition: "New",
    brand: "Air Jordan",
    isNewRelease: true,
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 13,
    shoe_name: "Air Jordan 1 Mid",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 120,
    condition: "New",
    brand: "Air Jordan",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 14,
    shoe_name: "Nike Air Force 1 Low",
    seller: "john.doe@gmail.com",
    size: "9",
    price: 100,
    condition: "Used",
    brand: "Nike",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 15,
    shoe_name: "Adidas Yeezy Boost 350 V2",
    seller: "john.doe@gmail.com",
    size: "11",
    price: 250,
    condition: "New",
    brand: "Adidas",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 16,
    shoe_name: "Nike Dunk Low",
    seller: "john.doe@gmail.com",
    size: "8.5",
    price: 150,
    condition: "New",
    brand: "Nike",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 17,
    shoe_name: "New Balance 550",
    seller: "john.doe@gmail.com",
    size: "10",
    price: 100,
    condition: "Used",
    brand: "New Balance",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 18,
    shoe_name: "Vans Old Skool",
    seller: "john.doe@gmail.com",
    size: "7.5",
    price: 50,
    condition: "New",
    brand: "Vans",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 19,
    shoe_name: "Converse Chuck Taylor All Star",
    seller: "john.doe@gmail.com",
    size: "9.5",
    price: 60,
    condition: "Used",
    brand: "Converse",
    color: "White",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 20,
    shoe_name: "Puma Suede Classic",
    seller: "john.doe@gmail.com",
    size: "8",
    price: 70,
    condition: "New",
    brand: "Puma",
    color: "Black",
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0e7fc8f3-76b7-4631-b147-4dad4b1ff241/air-jordan-1-mid-shoes-X5pM09.png",
  },
  {
    id: 21,
    shoe_name: "Nike Air Max Plus",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 180,
    condition: "New",
    brand: "Nike",
    color: "Black",
    isNewRelease: true,
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/877d30e7-4880-46f8-aa71-6704eb7d944d/air-max-plus-mens-shoes-x9G2xF.png",
  },

  {
    id: 22,
    shoe_name: "Freak 5",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 160,
    condition: "New",
    brand: "Nike",
    color: "Red",
    isNewRelease: true,
    image_url:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fa32a21a-2a41-4ea4-bf4d-41fca9886c02/freak-5-basketball-shoes-jZzrx4.png",
  },
  {
    id: 23,
    shoe_name: "ULTRABOOST 1.0 SHOES",
    seller: "john.doe@gmail.com",
    size: "10.5",
    price: 120,
    condition: "New",
    brand: "Adidas",
    color: "White",
    isNewRelease: true,
    image_url:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/f042b05ad1bf4d51b7dfaf1600054038_9366/Ultraboost_1.0_Shoes_White_HQ4202_01_standard.jpg",
  },
];

export const LANGUAGE_MAP = {
  en: {
    "Shop Now": "Shop Now",
    Browse: "Browser",
    Sell: "Sell",
    "About Us": "About Us",
    Profile: "Profile",
    Login: "Login",
    Signup: "Signup",
    Cart: "Cart",
    Logout: "Logout",
    "More Brands": "More Brands",
    "New Releases": "New Releases",
    "Popular Brands": "Popular Brands",
    "Find Our Socials": "Find Our Socials",
    "Download Our App": "Download Our App",
  },
  fr: {
    "Shop Now": "Achetez maintenant",
    Browse: "Parcourir",
    Sell: "Vendre",
    "About Us": "À propos de nous",
    Profile: "Profil",
    Login: "Connexion",
    Signup: "S'inscrire",
    Logout: "Se déconnecter",
    Cart: "Chariot",
    "More Brands": "Plus de marques",
    "New Releases": "Nouvelles versions",
    "Popular Brands": "Marques populaires",
    "Find Our Socials": "Trouvez nos réseaux sociaux",
    "Download Our App": "Téléchargez notre application",
  },
};
